SET FOREIGN_KEY_CHECKS=0;
INSERT IGNORE INTO wheelie_dynamic.country SELECT * FROM wheelie.country;
INSERT IGNORE INTO wheelie_dynamic.city SELECT * FROM wheelie.city;
INSERT IGNORE INTO wheelie_dynamic.address SELECT * FROM wheelie.address;
INSERT IGNORE INTO wheelie_dynamic.customer SELECT * FROM wheelie.customer;
-- INSERT IGNORE INTO wheelie_dynamic.rental SELECT * FROM wheelie.rental;
-- INSERT IGNORE INTO wheelie_dynamic.payment SELECT * FROM wheelie.payment;
-- INSERT IGNORE INTO wheelie_dynamic.service SELECT * FROM wheelie.service;
INSERT IGNORE INTO wheelie_dynamic.car SELECT * FROM wheelie.car;
INSERT IGNORE INTO wheelie_dynamic.equipment SELECT * FROM wheelie.equipment;
INSERT IGNORE INTO wheelie_dynamic.inventory SELECT * FROM wheelie.inventory;
INSERT IGNORE INTO wheelie_dynamic.inventory_equipment SELECT * FROM wheelie.inventory_equipment;
INSERT IGNORE INTO wheelie_dynamic.staff SELECT * FROM wheelie.staff;
INSERT IGNORE INTO wheelie_dynamic.store SELECT * FROM wheelie.store;
SET FOREIGN_KEY_CHECKS=1;
